add_newline = false

[character]
symbol = "âœ"
error_symbol = "âœ—"
use_symbol_for_status = true

[battery]

[git_branch]
symbol = "ğŸŒ±"
truncation_length = "4"
truncation_symbol = ""

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"

[git_status]
conflicted = "ïœ¿"
ahead = "ğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "â•"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ï¸"

[jobs]
symbol = "+ "

[nodejs]
symbol = "ï  "

[python]
pyenv_version_name = true

[rust]
symbol = "ğŸ¦€"
